### PR TITLE
Allow normal and tex indices to be zero + fix a warning

### LINKED ISSUE #348: Normal indices with a value of zero
**Describe the issue**
I know that this a strange request, but is it possible to support invalid (i.e. zero) normal indices? Currently I get the following error:
```
Failed parse `f' line(e.g. zero value for face index. line 70537.)
```
The problematic line looks like this:
```
f 22979/21114/0 22978/21108/3845 23110/21108/3853 23345/21115/3852 23346/21324/4037 23108/21323/3901
```
And it's not the only such line. In fact, it seems all the hexagons in this file have this issue. The file is generated by Cinema 4D, so it seems that their exporter is bugged (I couldn't find any easy way of reporting this issue to them).

**To Reproduce**
Unfortunately, I can't provide a sample .obj file due to the licensing.

**Expected behavior**
It would be nice if instead of aborting, the library provided invalid normal indices for such vertices, so I could handle these values in my code. Thanks.
```cpp
struct index_t {
  int vertex_index;
  int normal_index; // -1 here, for example
  int texcoord_index;
};
```

### PR DESCRIPTION
**Pull request by Trider12**
Fixes https://github.com/tinyobjloader/tinyobjloader/issues/348
Not the prettiest solution about warnings, so @syoyo feel free to change it.

### CODE REVIEW

**Comment by syoyo** [comment]
@Trider12 Awesome! Let me give some to review it

**Comment by syoyo** [comment]
@Trider12 Do you have a plan to add more changes?

**Comment by Trider12** [comment]
> @Trider12 Do you have a plan to add more changes?

@syoyo I think that's it. These fixes were made mostly because you are using `-std=c++03` flag in your tests.

**Comment by syoyo** [comment]
@Trider12 Thanks! Merged!

**Pull request merged**
