### PR TITLE
Prevent integer overflow in tryParseDouble

### PR DESCRIPTION
**Pull request by catenacyber**
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32861 found by oss-fuzz

### CODE REVIEW

**Comment by syoyo** [comment]
There is `INT_MAX` undefined compilation error: https://dev.azure.com/tinyobjloader/tinyobjloader/_build/results?buildId=143&view=logs&j=7ccdb770-8ced-59a9-27b9-05082213addd&t=6af9e0a9-b819-5b92-ea07-c11a47f13b4a&l=18

Please use `std::numeric_limits<int32_t>::max()` instead of using `INT_MAX`

**Comment by catenacyber** [comment]
Thanks, I thought I would have got a notification about the build failure...
Force-pushed the change

**Comment by syoyo** [comment]
@catenacyber Oh my bad. `int32_t` is available from C++11. Not supported in C++03 standard, so there is another compilation error: https://ci.appveyor.com/project/syoyo/tinyobjloader-6e4qf/builds/38569727#L25

Could you modify it to `std::numeric_limits<int>::max()` ?

**Comment by syoyo** [comment]
@catenacyber Awesome! Do you have a regression test data(.obj file) for this PR?

**Comment by catenacyber** [comment]
Would it be oss-fuzz input `v 3E4570711268` ?

**Comment by syoyo** [comment]
@catenacyber You can add it  to `fuzzer` folder of tinyobjloder repo if the filesize is small(e.g. less than 1 KB)

**Comment by catenacyber** [comment]
And then, how does it get run by CI ?

**Comment by syoyo** [comment]
Currently no Fuzzer regression tests on CI build. For a while, just run it on my local PC to confirm the issue has been solved before the merge.

We could extend `runner.py` script `https://github.com/tinyobjloader/tinyobjloader/blob/master/fuzzer/runner.py`  to run regressions  on CI. 

PR for Fuzzer regression tests on CI is also welcome!

**Comment by catenacyber** [comment]
Just added the input file for the fuzz target.
For CI regression integration, this input triggers a bug with UBSAN, not Address Sanitizer...
Is there such a build ?

**Comment by syoyo** [comment]
@catenacyber I have added simple regression test runner in this PR 

https://github.com/tinyobjloader/tinyobjloader/pull/304 

and confirmed the fix solves overflow issue on running regression tester on the local machine.

So close this PR.

Run regression tests on CI is TODO

**Pull request closed without merging**
