### PR TITLE
Avoid deallocating a shape that is added to `shapes`

### PR DESCRIPTION
**Pull request by paulmelnikow**

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi @syoyo, does this change look okay to you?

**Comment by syoyo** [comment]
@paulmelnikow What is the purpose of it? To reduce memory usage?

**Comment by syoyo** [comment]
@paulmelnikow `shape` data is copied to `shapes` so it does not have any side-effects(its safe to deallocate it implicitly)

BTW

```
 prim_group.clear();  // for safety
```

this line is also redundant. We may be better to delete it unless you are managing large .obj data and want to reduce memory usage as much as possible.

**Comment by paulmelnikow** [comment]
Hi @syoyo, I sent you an email about this.

**Comment by paulmelnikow** [comment]
This fix is invalid. See #358 instead.

**Pull request closed without merging**
