### PR TITLE
Fix parsing of comments at the end of lines for tokens with variable number of elements. (#389)

### PR DESCRIPTION
**Pull request by scschaefer**
This pull request should fix the problem described in issue #389 by cancelling the while loop when a `#` comment character is found.
Everything that follows after the `#` can be assumed to be part of the comment and should thus not be parsed.

### CODE REVIEW

**Comment by syoyo** [comment]
Thanks! PR should fix the issue #389.

I'd like to add an unit test of issue #389 to https://github.com/tinyobjloader/tinyobjloader/blob/release/tests/tester.cc
Is it ok to add linien.obj test scene in #389 to here https://github.com/tinyobjloader/tinyobjloader/tree/release/models ?

**Comment by scschaefer** [comment]
Thanks for the quick review! 🙂
Adding the file to the models folder should be fine. 👍

**Comment by syoyo** [comment]
Thanks! PR has been merged, and added a regression test in this commit: https://github.com/tinyobjloader/tinyobjloader/commit/fe9e7130a0eee720a28f39b33852108217114076

**Comment by scschaefer** [comment]
Thank you for merging my PR! 🙂
Could you please tag commit fe9e713 as `v2.0.0rc14`?

We use tinyobjloader via [vcpkg](https://vcpkg.io/en/package/tinyobjloader), and a new version tag would make it much easier to submit a pull request to update the vcpkg port.

Thanks again for your time!

**Comment by syoyo** [comment]
I don't recommend to use vcpkg, since tinyobjloader is header-only library. Copying a header file is the recommended way.

**Comment by scschaefer** [comment]
While I agree with you, I don't have a choice, as our approved workflow mandates using vcpkg for our C++ backend. We use vcpkg not just to include external packages but also to automatically parse the packages' meta-info to check whether the necessary licenses are included in our setup, the package's version is up to date, etc. That wouldn't work if I included the header directly in our solution. 🤔

**Pull request merged**
