### PR TITLE
Reject invalid relative indices (fix TALOS-2020-1212)

### PR DESCRIPTION
**Pull request by paulmelnikow**
This PR is meant to address reported security vulnerability [TALOS-2020-1212](https://talosintelligence.com/vulnerability_reports/TALOS-2020-1212), which states:

> An improper array index validation vulnerability exists in the LoadObj functionality of tinyobjloader v2.0-rc1 and tinyobjloader development commit 79d4421. A specially crafted file could lead to code execution. An attacker can provide a malicious file to trigger this vulnerability.

The loader has support for negative face indexes per the Wavefront OBJ spec. However, there is no guard on the range of the relative indexes. If a parsed OBJ specifies a relative index which isn't there, `fixIndex()` returns an invalid negative index, which means these invalid indexes (e.g. -4, -2, etc). are placed into in the attrib_t::vertices structure.

This produces the security vulnerability referenced above.

This PR ensures that invalid relative indexes are rejected by the parser.

Co-authored with @jbeard4

### CODE REVIEW

**Comment by syoyo** [comment]
@paulmelnikow Awesome! Confirmed the issue and PR fixes it, so merged!

TODO:  For invalid relative vertex index, it should report an error. But for normal and texture index, it'd may be better to allow invalid relative index. e.g. set `-1` for invalid index, report warn, and let app/user deal with it, as we set `-1` for zero index value for normal/texture https://github.com/tinyobjloader/tinyobjloader/issues/348

**Comment by paulmelnikow** [comment]
Awesome, thank you! Would you like a follow-on PR to address that?

**Comment by syoyo** [comment]
@paulmelnikow I think it'd be better to add a parameter(e.g. `allow_invalid_relative_normal_index`) to ObjReaderConfig https://github.com/tinyobjloader/tinyobjloader/blob/0fc802cf468d23b9d205890b76b268f61b948e6d/tiny_obj_loader.h#L505 to how to treat the parsing behavior for invalid relative normal/texture index: 

Default behavior(and legacy v1 API): Make an error for invalid relative normal/texture index.

**Comment by paulmelnikow** [comment]
Okay, then I'll leave it as an open todo for now.

**Pull request merged**
